// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeIDilvF4Khbm7uorBhNauTnctMc_CnCc',
    appId: '1:473227743228:web:0562cef856140f304f2c79',
    messagingSenderId: '473227743228',
    projectId: 'takequiz-6484b',
    authDomain: 'takequiz-6484b.firebaseapp.com',
    storageBucket: 'takequiz-6484b.appspot.com',
    measurementId: 'G-BRX4J5K8K9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC58lP4VhvJpmLF3F19zwG8N1xczK5fi8E',
    appId: '1:473227743228:android:70ac44894a86906e4f2c79',
    messagingSenderId: '473227743228',
    projectId: 'takequiz-6484b',
    storageBucket: 'takequiz-6484b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwRLmm-L4Cgf1GXyWLblCvhQIQSZPGRlI',
    appId: '1:473227743228:ios:a050749819cf32f14f2c79',
    messagingSenderId: '473227743228',
    projectId: 'takequiz-6484b',
    storageBucket: 'takequiz-6484b.appspot.com',
    iosClientId: '473227743228-rir54is82lnmll26illp2f5lg4k28pft.apps.googleusercontent.com',
    iosBundleId: 'com.example.takequiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwRLmm-L4Cgf1GXyWLblCvhQIQSZPGRlI',
    appId: '1:473227743228:ios:a050749819cf32f14f2c79',
    messagingSenderId: '473227743228',
    projectId: 'takequiz-6484b',
    storageBucket: 'takequiz-6484b.appspot.com',
    iosClientId: '473227743228-rir54is82lnmll26illp2f5lg4k28pft.apps.googleusercontent.com',
    iosBundleId: 'com.example.takequiz',
  );
}
